### ISSUE TITLE
The purpose of apollo.js?

### ISSUE THREAD

**Issue by DrSensor** [Akryum/vue-cli-plugin-apollo#10]
Hello,

I'm an early test this plugin adding it to my typescript project generated by vue/cli 3.0.0-beta.6 .
As I clean up, I found `src/apollo.js` not imported in anywhere. I wonder what `apollo.js` function is?

I choose `? Add a GraphQL API Server? No`

<details>
<summary></summary>

> Just info: `src/vue-apollo.js` is imported in `main.ts` as it should be.
</details>

Regards.

**Comment by Akryum** [comment]
It is imported in `vue-apollo` [here](https://github.com/Akryum/vue-cli-plugin-apollo/blob/3834af5d4fa6528aa68f054b09fa2ac6e604791e/generator/templates/default/src/vue-apollo.js#L3)

**Comment by DrSensor** [comment]
Thanks for the quick response. I will close the issue :)

<details>
<summary>some suggestion from user perspective who just read it :innocent: </summary>

I get the gist what `apollo.js` do. Majorly it create all in one mode apollo client.
However, I found it too long and confusing to do the modification. Maybe split the generated code and prompt in:
- authentication
- WebSocket support
- caching?
- SSR mode
will do the trick
</details>
