### ISSUE TITLE
Multiple Clients with SSR - wrong state restored

### ISSUE THREAD

**Issue by JohannesLamberts** [Akryum/vue-cli-plugin-apollo#110]
The cache-restore doesn't work after SSR, if multiple clients where created.
The graphql-client always tries to restore from the defaultClient.

https://github.com/Akryum/vue-cli-plugin-apollo/blob/f0e320da72ffc55ccb86e91d7c317f76509e0b50/graphql-client/src/index.js#L90

I would suggest to not restore the cache in case a custom cache implementation had been provided.
Another way would be to add a `clientKey` / `restoreStateKey` option.

(vue-cli-plugin-apollo@0.19.1)

**Comment by svewag** [comment]
This makes totally sense. I'm really looking forward to see this in the next release.
