### ISSUE TITLE
How to set credentials value correctly?

### ISSUE THREAD

**Issue by georgyfarniev** [Akryum/vue-cli-plugin-apollo#115]
Hello. It's totally unclear from documentation how to set **credentials** value to **include**. Tried to achieve it passing the following options to createApolloClient:

```
  credentials: 'include',
  httpLinkOptions: {
    credentials: 'include'
  }
```

But there's no effect. How can I enable apollo to send cookies to backend for authentication? It's very critical part.

**Comment by Akryum** [comment]
Just `httpLinkOptions` with `credentials: 'include'` is enough. It is passed to [createUploadLink](https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink).

**Comment by georgyfarniev** [comment]
> Just `httpLinkOptions` with `credentials: 'include'` is enough. It is passed to [createUploadLink](https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink).

It has no effect by some reason, but I solved this problem by creating ApolloClient directly, instead of using this plugin. Thanks. Closing it.
