### ISSUE TITLE
allow defining custom connectionParams for websocket connection

### ISSUE THREAD

**Issue by praveenweb** [Akryum/vue-cli-plugin-apollo#134]
Currently the connectionParams in subscriptionClient always returns either of `authorization` or an empty object depending on the availability of the token. [Source here](https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js#L112)

This convention doesn't work with [Hasura GraphQL Engine](https://github.com/hasura/graphql-engine) as Hasura expects a `header` object to be returned in connectionParams with authorization key inside the object.

So this is what works with Hasura:

```
wsClient = new SubscriptionClient(wsEndpoint, {
  reconnect: true,
  connectionParams: () => {
    const authorization = getAuth(tokenName)
    return authorization ? { headers: { authorization } } : {}
  },
})
```

Note the authorization object wrapped in a top level headers key.

I think it's better not to assume any convention in the way connectionParams is handled, since different servers will have different ways to handle this.

I would like the plugin to allow the user to define their custom method for `connectionParams`, similar to `getAuth`.

**Comment by thetre97** [comment]
Related to https://github.com/Akryum/vue-apollo/issues/520

**Comment by gitxav** [comment]
Related to https://github.com/Akryum/vue-cli-plugin-apollo/issues/187

**Comment by Akryum** [comment]
Duplicate of the vue-cli-plugin-apollo issue.

**Comment by drewbaker** [comment]
@Akryum Which issue is this a duplicate of? I really need connectionParams on websockets, so I want to follow the progress of the underlying issue.
