### ISSUE TITLE
Can't import the namespace object from non EcmaScript module

### ISSUE THREAD

**Issue by mbj36** [Akryum/vue-cli-plugin-apollo#18]
Hi @Akryum Thanks for this plugin, I am getting this error on running `npm run serve`

<img width="726" alt="screen shot 2018-05-11 at 10 01 02 pm" src="https://user-images.githubusercontent.com/9936881/39935486-c36eebf0-5566-11e8-8517-8eecf4d12de0.png">

**Comment by bblumberg** [comment]
I encountered the same problem. I am using vue 3.0.0 beta 9. Thanks for the plugin, I think it will be very useful.

**Comment by davefollett** [comment]
I was able to workaround this issue by forcing the `apollo-upload-client` to the latest released version..  Everything seems OK so far.

```npm install apollo-upload-client@8.0.0```

 `apollo-upload-client` fixed this issue here: https://github.com/jaydenseric/apollo-upload-client/issues/72
