### ISSUE TITLE
typescript can't find module .gql

### ISSUE THREAD

**Issue by franciscolourenco** [Akryum/vue-cli-plugin-apollo#180]
It works fine if you change the language to js.

```
ERROR in /Users/user/code/reproduce-typescript-vue-cli-plugin-apollo/src/components/ApolloExample.vue
97:19 Cannot find module '../graphql/Files.gql'.
     95 |
     96 | <script lang="ts">
  >  97 | import FILES from "../graphql/Files.gql";
        |                   ^
     98 | import UPLOAD_FILE from "../graphql/UploadFile.gql";
     99 |
    100 | export default {
ERROR in /Users/user/code/reproduce-typescript-vue-cli-plugin-apollo/src/components/ApolloExample.vue
98:25 Cannot find module '../graphql/UploadFile.gql'.
     96 | <script lang="ts">
     97 | import FILES from "../graphql/Files.gql";
  >  98 | import UPLOAD_FILE from "../graphql/UploadFile.gql";
        |                         ^
     99 |
    100 | export default {
    101 |   data() {
```

vue cli reproduction: https://github.com/reproducing/reproduce-typescript-vue-cli-plugin-apollo

**Comment by jbbr** [comment]
@Akryum this implementation causes issue when used with tools Graphql Codegen (Module Plugin: https://graphql-code-generator.com/docs/plugins/typescript-graphql-files-modules ).
Sometimes it's also desirable to use "*.graphql" as an any-module, which allows arbitrary imports.
e.g: `import {myQuery, otherQuery} from 'queries.graphql'`

Unfortunately Typescript doesn't have an option for excluding specific types. Only whitelist approach via `types: []` in tsconfig. For this reason I had to downgrade `vue-apollo`.

I'd argue for these reasons this kind of type definition shouldn't be part of `vue-apollo`.
What do you think?
