### ISSUE TITLE
graphql-client token was stored in localStorage then won't work in SSR?

### ISSUE THREAD

**Issue by kieusonlam** [Akryum/vue-cli-plugin-apollo#22]
Hi, sorry if I ask a stupid question. I have not tried it yet, but I see the token was stored in localStorage, then it will not work in SSR right? If so, is there anyway to do to make token work with SSR?

**Comment by Akryum** [comment]
You can use cookies instead or with `localStorage` already!

**Comment by kieusonlam** [comment]
I see. I saw it, the option to write my own getAuth funtion.
https://github.com/Akryum/vue-cli-plugin-apollo/blob/65b54a399efc689515618dbb8086f145c5b60677/graphql-client/src/index.js#L26

**Comment by Akryum** [comment]
You don't even need to override this to use Cookie. :wink:

**Comment by kieusonlam** [comment]
Sorry for boring you again,

I'm trying to rewrite nuxt `apollo-module` with this. I got stuck with localStorage

```
networkError: ReferenceError: localStorage is not defined
    at defaultGetAuth (server-bundle.js:2942:15)
    at server-bundle.js:2830:26
    at C:\Users\Lenovo\Desktop\movie-web\node_modules\apollo-link-context\lib\bundle.umd.js:22:51
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7),
  message: 'Network error: localStorage is not defined',
  extraInfo: undefined,
  statusCode: 500,
  name: 'NuxtServerError' }
```

Here is my repo: https://github.com/kieusonlam/apollo-module

**Comment by Akryum** [comment]
Hmm you'll need to put the `getAuth: () => undefined` option.

**Comment by ShourovRoy** [comment]
save it in cookies and in SSR context you can access that cookie token
