### ISSUE TITLE
using apollo-client config as dependency for NuxtJS apollo-module

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-cli-plugin-apollo#24]
@Akryum in this PR (https://github.com/nuxt-community/apollo-module/pull/106) we try to generalize the integration with vue-apollo similar to your approach in the vue-cli-plugin-apollo. One question though - will it be save to call the plugin within this package as follow:
```
import { createApolloClient, restartWebsockets } from 'vue-cli-plugin-apollo/graphql-client'
```
This would generalize the same behaviour for vue-apollo users either using NuxtJs or the vue-cli

Thanks!

**Comment by Akryum** [comment]
It should work.

**Comment by dohomi** [comment]
great thanks for your efforts the plugin works great!
