### ISSUE TITLE
Redirecting on 401 error

### ISSUE THREAD

**Issue by frandiox** [Akryum/vue-cli-plugin-apollo#27]
@Akryum Hi! I'd like to catch 401 errors and redirect to `/login` or fetch another token automatically. I've been [searching](https://github.com/apollographql/apollo-link/issues/297) and looks like it is possible to create an apollo http link to do this, but seems rather complex.

Do you recommend passing `link` or `apollo` to `createServer` in this plugin or know a better way? Perhaps an error handler could be exposed in `vue-apollo`? Thanks!

**Comment by Akryum** [comment]
See [the docs](https://github.com/Akryum/vue-apollo#constructor) for handling error globally.

**Comment by bbugh** [comment]
The docs for this moved here: https://akryum.github.io/vue-apollo/api/apollo-provider.html#constructor

Relevant code:

```js
const apolloProvider = new VueApollo({
  // ...,
  // Global error handler for all smart queries and subscriptions
  errorHandler (error) {
    console.log('Global error handler')
    console.error(error)
  },
})
```

Note that this doesn't work for mutations.

You can also set up a client-level catcher with [apollo-link-error](https://www.npmjs.com/package/apollo-link-error) but it's less friendly as you can get into an unrecoverable state with network errors. Might work better for what you want if you need a truly catch-all error handler.

**Comment by ralph** [comment]
Note that the docs moved here as of now (2020):
https://vue-apollo.netlify.com/api/apollo-provider.html
