### ISSUE TITLE
support apollo-link-error onError

### ISSUE THREAD

**Issue by aldarund** [Akryum/vue-cli-plugin-apollo#29]
Im using a nuxt-apollo module. In version 3 i was able to use apollo-link-error like this:
```
const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (networkError) {
      ctx.app.$messages.showErrorMessage(networkError.message)
    }

  })
```

But v4 now use vue-cli-plugin-apollo and it seem there no option to use apollo-link-error anymore.

https://github.com/nuxt-community/apollo-module/issues/115#issuecomment-397125833

**Comment by Akryum** [comment]
Use the `link` option to provide custom links.

**Comment by alaarihan** [comment]
I tried with this but I don't know how it should be configured, here is my config
```
import { onError } from 'apollo-link-error'
const onErrorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]!!: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    )
  if (networkError) console.log(`[Network error]!!!: ${networkError}`)
})

function createApolloClient ({
 ...
  link = onErrorLink,
...
})
```
I get this error message:
Error while mounting app: TypeError: x.concat is not a function

**Comment by Tinoooo** [comment]
@alaarihan Did you find a solution for the error?

**Comment by Tinoooo** [comment]
@alaarihan This might be the reason for your error: https://github.com/nuxt-community/apollo-module/issues/306
