### ISSUE TITLE
vue-cli commands dont exit correctly when upgrading vue-cli-plugin-apollo from v0.13.7 to v0.13.8

### ISSUE THREAD

**Issue by leovanhaaren** [Akryum/vue-cli-plugin-apollo#31]
See related issue here, other seem to experience the same problem;
https://github.com/vuejs/vue-cli/issues/1622

@Akryum any idea why this happens?

**Comment by leovanhaaren** [comment]
Thanks for fixing this @Akryum ur the best!

**Comment by thetre97** [comment]
ditto! 👍 👍 👍
