### ISSUE TITLE
Blank authorization header causing issues with Postgraphile API

### ISSUE THREAD

**Issue by timhanlon** [Akryum/vue-cli-plugin-apollo#35]
Until a token is set, an empty authorization header is being sent:

```
POST /graphql HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 308
accept: */*
Origin: http://localhost:3000
authorization:
```

This is causing an issue with Postgraphile, which is expecting a bearer token if the authorization header is present.

Would you accept a PR which doesn't send the authorization header if a token isn't set?

**Comment by Akryum** [comment]
Sure! 😸

**Comment by moltar** [comment]
Having the same issue. @timhanlon are you working on the PR still?

**Comment by moltar** [comment]
We just need to set the header conditionally: https://github.com/Akryum/vue-cli-plugin-apollo/blob/e2eb14b2c33ec3dd97180218ae923b9934de0251/graphql-client/src/index.js#L49

**Comment by timhanlon** [comment]
@moltar I haven't had time to work on it yet. You can patch `graphql-client/dist/index.js` in the meantime:

```
    if (getAuth(tokenName) !== '') {
      authLink = setContext(function (_, _ref2) {
        var headers = _ref2.headers;
        return {
          headers: _objectSpread({}, headers, {
            authorization: getAuth(tokenName)
          })
        };
      }); // Concat all the http link parts
    } else {
      authLink = setContext(function (_, _ref2) {
        var headers = _ref2.headers;
        return {
          headers: _objectSpread({}, headers, {

          })
        };
      }); // Concat all the http link parts  
```

**Comment by moltar** [comment]
Fix https://github.com/Akryum/vue-cli-plugin-apollo/pull/38
