### ISSUE TITLE
No gql loader

### ISSUE THREAD

**Issue by fnoop** [Akryum/vue-cli-plugin-apollo#4]
This doesn't seem to install the gql loader.  I had to install the loader by hand into build/webpack.base.conf.js, with the rest of the loaders in module: rules:, then it worked:
```
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader'
      }
```

**Comment by Akryum** [comment]
You need vue-cli 3.x and a project created with it to use this plugin.

**Comment by fnoop** [comment]
Again, this was with vue-cli 3.0.0-alpha13 and a brand new vue template created for testing and double checking this issue.  After npm install I searched through the whole project for any sign of graphql-tag and the only mention was in the cli templates, not in the project itself.  When I added the above lines in by hand it's all started working.
But I tried in several projects, new and old, with vue-cli 3, and none of the had the loader added.

**Comment by Akryum** [comment]
This is where the loader is added to the webpack configuration: https://github.com/Akryum/vue-cli-plugin-apollo/blob/d284502b7249755242fbe50ed6960fd180daa78c/index.js#L13-L23
Are you using `vue-cli-service serve`? Did you install the `vue-cli-plugin-apollo` package into your project or globally? Did you try create a brand new project and tested the `ApolloExample.vue` component which is using `.gql` files?

**Comment by fnoop** [comment]
I'm using https://github.com/vuejs-templates/pwa (actually https://github.com/vuetifyjs/pwa, a close fork), and vue init ... to create my project.  This doesn't have a 'serve' target, so running `npm run dev`.
Adding vue-cli-plugin-apollo as per instructions: `npm i -D vue-cli-plugin-apollo`
The problme is the gql loader isn't being installed anywhere - I install it into the boilerplate build/webpack.base.conf.js module: rules: section, there may be somewhere better.

**Comment by Akryum** [comment]
You need to use vue-cli 3 `create` command and then proceed with installing vue-cli-plugin-apollo. `vue init` is a legacy command, which is still present in vue-cli 3 for backward-compatibility purposes.

**Comment by syed-haroon** [comment]
for someone who lands here while setting graphql manually, check this [URL](https://cli.vuejs.org/guide/webpack.html#adding-a-new-loader) or refer below code:

```
// vue.config.js
module.exports = {
  chainWebpack: (config) => {
    // GraphQL Loader
    config.module
      .rule('graphql')
      .test(/\.(graphql|gql)$/)
      .use('graphql-tag/loader')
      .loader('graphql-tag/loader')
      .end();
  },
};

```
