### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by negezor** [Akryum/vue-cli-plugin-apollo#40]
Prior to updating apollo-modules, a link was manually created there, but after using to vue-cli-plugin-apollo, the download stopped working. But it only worked for me when I manually created the upload link.
```js
import uploadClient from 'apollo-upload-client';
import cacheInMemory from 'apollo-cache-inmemory';

import introspectionQueryResultData from './fragmentTypes.json';

export default ({ env }) => {
	const fragmentMatcher = new cacheInMemory.IntrospectionFragmentMatcher({
		introspectionQueryResultData
	});

	const cache = new cacheInMemory.InMemoryCache({
		fragmentMatcher
	});

	const graphqlUrl = `${env.PUBLIC_URL}/graphql`;

	const link = uploadClient.createUploadLink({
		uri: graphqlUrl
	});

	return {
		httpEndpoint: graphqlUrl,
		cache,
		link
	};
};
```
I think the problem is that the download link should be created first.

**Comment by mattwr18** [comment]
Hey @negezor, did you get this working?
@Akryum could you maybe give a reason why you closed this?
Can we use `apollo-upload-client` with `vue-cli-plugin-apollo`?
Could you perhaps point to any examples?

**Comment by mattwr18** [comment]
Sorry @Akryum, I can see that you are using `apollo-upload-client` under the hood https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js#L3

Thanks for the great library
