### ISSUE TITLE
"Running the server in production" has more dependencies

### ISSUE THREAD

**Issue by caugner** [Akryum/vue-cli-plugin-apollo#41]
[According to the README](https://github.com/Akryum/vue-cli-plugin-apollo#running-the-graphql-server-in-production), it should suffice to move `vue-cli-plugin-apollo` from the `devDependencies` to the `dependencies`.

Unforatunately however, the command  `vue-cli-service apollo:run --mode production` not only requires `@vue/cli-service`, but also all other `@vue/cli-plugin` to be moved. Otherwise `Service.resolvePlugins` runs into an `Cannot find module '@vue/cli-plugin-*` error. Here's what I did:

```console
rm -rf node_modules
yarn install --prod
yarn run vue-cli-service apollo:run --mode production
```

Would it be a realistic solution to add an `apollo:build` task that builds the server with all dependencies to `apollo-server/dist` or is that out of scope?

**Comment by Akryum** [comment]
I need to improve this section. If you want to use the server in a library-like package, you should move the vue-cli-plugin-apollo dep so you can run the server ([example](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-ui/server.js)).

If it's a regular app you want to run in production, you can either not move the deps around at all and use `yarn install`, or  if you really want to use the `prod` flag on yarn, move `@vue/cli-service` to `dependencies` as well. (Note that for example now.sh install everything by default.)
