### ISSUE TITLE
Unexpected token import -  ESM in dist files

### ISSUE THREAD

**Issue by frandiox** [Akryum/vue-cli-plugin-apollo#43]
Hi! Some distribution files contain ES modules: https://unpkg.com/vue-cli-plugin-apollo@0.15.0/graphql-client/dist/index.js

Is this intended? It breaks Jest since it doesn't transpile `node_modules` by default.

As a workaround, renaming `.babelrc` to `.babel.config.js` and using `transformIgnorePatterns` in Jest's config make it work again. [More details here](https://github.com/frandiox/vue-graphql-enterprise-boilerplate/pull/32).

Thanks!

**Comment by frandiox** [comment]
My `LoginView` imports `onLogin` and `onLogout` from `vue-apollo.js`. That file, at the same time, imports stuff from `vue-cli-plugin-apollo`: https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/generator/templates/vue-apollo/default/src/vue-apollo.js#L3

**Comment by Akryum** [comment]
Then you should mock those. https://jestjs.io/docs/en/manual-mocks

**Comment by frandiox** [comment]
Thanks for the prompt answer. I assume you mean this is intended then 👍 

For now, I think I prefer adding `transformIgnorePatterns` instead of mocking every test related to Apollo. Perhaps this could be useful for somebody else.

Thanks.
