### ISSUE TITLE
Error: You are calling concat on a terminating link, which will have no effect

### ISSUE THREAD

**Issue by gcoda** [Akryum/vue-cli-plugin-apollo#47]
When trying to `createApolloClient({ link: retryLink })`

changed a line in [graphql-client/src/index.js](https://github.com/Akryum/vue-cli-plugin-apollo/blob/4dbdd34ad92a0c0d86799af35bda02c640ff6a48/graphql-client/src/index.js#L46
) from `link = httpLink.concat(link)` to `link = from([link, httpLink])`
and it works fine

**Comment by dohomi** [comment]
@gcoda @Akryum this did not solve the issue for me. I am using `createUploadLink` from the package `apollo-upload-client`and still see the error of terminating link.
```js
import {createUploadLink} from 'apollo-upload-client'

createApolloClient({
      link: createUploadLink({uri: uploadEndpoint}),
})
``` 
I don't know where exactly to look for but the console warn wasn't there before I upgraded from `v 0.15` to `v 0.16.2`

**Comment by Akryum** [comment]
@dohomi There is already an upload client in the config.

**Comment by oller** [comment]
Thanks for that comment @mekhami .

I'm wondering what's the way to go about my scenario where I need to use `apollo-link-rest` alongside `apollo-link-http`?

If i define both in the `link` attribute - i'll get the above warning as i'm as i'm declaring httpLink again, but presumably as I'm overriding apollo-link and I still need `httpLink` I do need to declare it again?

Any advice @Akryum?

Thank you in advance!

**Comment by dmitry** [comment]
@eddivalen you have to use only `createApolloClient({ link: retryLink })`, as it calls `new HttpLink` inside of it.

**Comment by StupidSexyJake** [comment]
I'm getting the same error...

    // Create Apollo Client
    const client = new ApolloClient({
        connectToDevTools: process.browser,
        ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
        link: ApolloLink.from([
            authLink,
            terminatingLink,
            errorLink,
        ]),
        cache: new InMemoryCache().restore(initialState || {}),
    })

Error message:

    Error: You are calling concat on a terminating link, which will have no effect

**Comment by dmitry** [comment]
I believe one of the: authLink, terminatingLink, errorLink are calling the `HttpLink` inside of them.

**Comment by heshamelmasry77** [comment]
nothing is working. 
I have this :
import { ApolloLink } from 'apollo-link'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'

export default ctx => {
  // Cheki Staging GraphQL
  const httpLink = new HttpLink({
    uri: 'https://ch-ke-staging6.oam.cool/graphql',
  })

  // Middleware / will apply once auth is required
  const middlewareLink = new ApolloLink((operation, forward) => {
    // const token = process.server ? ctx.req.session : window.__NUXT__.state.session
    operation.setContext({
      // Remove for now until auth has been set up
      // headers: { authorization: `Bearer ${token}` }
      headers: {
        Authorization: `some token`
        umt: `dsdsd`,
      },
    })
    return forward(operation)
  })
  const link = middlewareLink.concat(httpLink)
  return {
    link,
    cache: new InMemoryCache(),
  }
}

**Comment by StupidSexyJake** [comment]
You're creating an Apollo Link instead of an Apollo Client.

Try this (not tested so might be a few typos/bugs):

```
export default ctx => {

  // Create the HTTP link
  const httpLink = new HttpLink({
    uri: 'my url',
  })

  // Create an auth link to set headers for each request
  const authLink = setContext((_, { headers }) => {
     return {
       headers: {
          ...headers,   // Include any existing headers
          Authorization: `some token`,
          umt: `dsdsd`,
       }
     }
  })

  // Concat links
  const link = authLink.concat(httpLink)

  // Return the new Apollo Client
  return new ApolloClient({
    link,
    cache: new InMemoryCache(),
  }
}
```

**Comment by linonetwo** [comment]
Getting same error from :

```
import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloLink } from 'apollo-link';
import { createUploadLink } from 'apollo-upload-client';
import { createHttpLink } from 'apollo-link-http';
import { onError } from 'apollo-link-error';

import config from '../../config/serviceConfig';

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: ApolloLink.from([
    onError(({ graphQLErrors, networkError }) => {
      if (graphQLErrors)
        graphQLErrors.map(({ message, locations, path }) =>
          console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`),
        );
      if (networkError) console.log(`[Network error]: ${networkError}`);
    }),
    createUploadLink({ uri: config.graphqlEndpoint }),
    createHttpLink({ uri: config.graphqlEndpoint }),
  ]),
});

export default client;

```

I think this error message is useless, is not helpful at all.

**Comment by jonasdumas** [comment]
+1

**Comment by jonasdumas** [comment]
I solve the problem by changing the order of links. HttpLink need to go at the end and it solve the problem for me:
**BEFORE**: from([ httpLink, errorLink, authLink,  ]) => _Bug_
**AFTER**: from([ errorLink, authLink, httpLink  ]) => _Works_

**Comment by tarunmangukiya** [comment]
I am still seeing this error with v0.21.3. I am using it with nuxt-apollo module.

**Comment by enzonotario** [comment]
Hi @tarunmangukiya , try with something like this:
```
import { BatchHttpLink } from 'apollo-link-batch-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { onError } from 'apollo-link-error';
import { ApolloLink } from 'apollo-link';

export default function createApolloClient(context) {
  // Create your custom client...
  const cache = new InMemoryCache();
  const batchHttpLink = new BatchHttpLink({
    uri: process.env.GRAPHQL_ENDPOINT,
  });
  const errorHandler = onError(({ networkError, graphQLErrors }) => {
    // ...
  });

  return {
    link: ApolloLink.from([errorHandler, batchHttpLink]),
    cache,
    defaultHttpLink: false, // <--- ADD THIS
  };
}
```

**Comment by seandelaney** [comment]
> defaultHttpLink: false, // <--- ADD THIS

What does this do?

**Comment by enzonotario** [comment]
check docs: https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/docs/guide/configuration.md

**Comment by ratrateroo** [comment]
This is my client, I removed the httpLink at the and the concat warning in my browser is gone.

export const client = new ApolloClient({
	link: ApolloLink.from([authLink, uploadLink]),
	cache: new InMemoryCache(),
});

Seems like uploadLink have httpLink inside of it already.
