### ISSUE TITLE
Can't import .gql files out of the box

### ISSUE THREAD

**Issue by ffxsam** [Akryum/vue-cli-plugin-apollo#48]
Created a fresh project via `vue create apollo` and didn't add any extra options (just Babel). Installed this plugin, ran `yarn serve`, and I can see there's no graphql loader:

```
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected character '#'

> 1 | #import "./FileFragment.gql"
    | ^
  2 |
  3 | mutation uploadFile ($file: Upload!) {
  4 |   singleUpload (file: $file) { at src/graphql/UploadFile.gql:1:1:
> 1 | #import "./FileFragment.gql"
    | ^
  2 |
  3 | mutation uploadFile ($file: Upload!) {
  4 |   singleUpload (file: $file) {
```

**Comment by Akryum** [comment]
Did you add vue-cli-plugin-apollo?

**Comment by ffxsam** [comment]
@Akryum Yes, of course

**Comment by Akryum** [comment]
What is the outputof `vue inspect`?

**Comment by ffxsam** [comment]
See below. I can put up a repository if you need, but literally all I did was create a new project, add the plugin (with example code), put `<apollo-example />` inside the HelloWorld component, and run `yarn serve`.

Vue inspect output: https://gist.github.com/ffxsam/7d0171fb260368715f67048c648e2b75

**Comment by Akryum** [comment]
The config is fine so can share the repo so I can reproduce.

**Comment by Akryum** [comment]
Okay, it seems there is an issue with eslint. It shouldn't prevent you to built the project in the meantime.

**Comment by marhub** [comment]
same error here. Basic project...

**Comment by orblazer** [comment]
Hello, is it probably same issue.

I have add apollo with web panel to my project plugin but when i want import `.gql` file i can't.
This is import line : `import auth from '@/graphql/auth.gql'`
This is error : `The module '@/graphql/auth.gql' is not found`

Note : I use typescript.

Thanks.

**Comment by fakedob** [comment]
As you can see from the [vue docs](https://cli.vuejs.org/guide/webpack.html#adding-a-new-loader), you have to include the graphql loader in the webpack (scroll down to "Adding a New Loader" in the advanced section). By doing so, Vue will start using the loader. Keep in mind the example is using .graphql instead of .gql, so you may want to change that.

As for the eslint part, as it states[ in the docs](https://github.com/apollographql/eslint-plugin-graphql), you should manualy add the extention using the cli by runninng `eslint . --ext .gql`

**Comment by orblazer** [comment]
@fakedob I have try multiple codes and i current have in `vue.config.js` :
```js
chainWebpack (config) {
  // GraphQL Loader
  config.module
    .rule('graphql')
    .test(/\.(graphql|gql)$/)
    .use('graphql-tag/loader')
    .loader('graphql-tag/loader')
    .end()
}
```

And i have try this for correct bug in IDE :
```ts
declare module '@/store/user.gql' {
  import { DocumentNode } from 'graphql'

  export const allUsers: DocumentNode
  export const deleteUser: DocumentNode
}
```

And know i have that error on build (no error in IDE) :
```
This dependency was not found:

* @/store/user.gql in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/admin/users/List.vue?vue&type=script&lang=ts&

To install it, you can run: npm install --save @/store/user.gql
```

Thanks.

**Comment by imd-solutions** [comment]
Hi,
Not sure if this is the same issue, but I am struggling to import an external file to the schema.graphql. (i.e a mutation: extend type Mutation { addUser(name: "test user"): User}).
Everything works fine with the mutation in the schema file.
Would be gratefull for some advise or a push in the right direction.

**Comment by franciscolourenco** [comment]
@orblazer tracking you issue here eslint-plugin-graphql

**Comment by franciscolourenco** [comment]
This issue can be fixed by installed and configuring [eslint-plugin-graphql](https://www.npmjs.com/package/eslint-plugin-graphql).

```bash
yarn add --dev eslint-plugin-graphql
```

The most minimal configuration is:

```javascript
// eslintrc.js

{
	//...
	plugins: [
		'graphql'
	]
}
```

Let me know if this fixed the issue.

**Comment by MuhaddiMu** [comment]
+1 `eslintrc.js` needs to be strictly fixed when adding Vue apollo without demo code or server configuration. It wasted alot of time. Unable to find any solution. On each change, I manually inspect code and remove the warning Iframe page.

**Comment by Akryum** [comment]
Should be fixed in the upcoming release.
