### ISSUE TITLE
type error lastIndexOf undefined if not running apollo-server

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-cli-plugin-apollo#49]
Hi
I run my server in a different project and with `vue ui` I see following error message in the console:
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at exports.resolveModuleRoot (/Users/d/.nvm/versions/node/v8.11.2/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/util/resolve-path.js:5:28)
```
Is there a way to entirely disable the use of apollo-server? I tried `apollo:false` with no effect so far. Thanks

**Comment by Akryum** [comment]
Vue CLI UI uses apollo-server internally. This seems more related to https://github.com/vuejs/vue-cli
