### ISSUE TITLE
Breaking in mjs enabled webpack 4 environments

### ISSUE THREAD

**Issue by aldarund** [Akryum/vue-cli-plugin-apollo#57]
This is effectively break https://github.com/nuxt-community/apollo-module with latest nuxt-edge, because nuxt-edge have an mjs enabled 
https://github.com/nuxt/nuxt.js/issues/3892
https://github.com/nuxt-community/apollo-module/issues/159
It ends up with invalid code in browser
```
 function(e, t, n) {
    "use strict";
    (function(e) {
        t.a = function(e, t) {
            return e instanceof t
        }
    }
    ).call(this, require("./../../process/browser.js"))
```

Updating graphql to 14.0.2 make the error go away with mjs enabled.

**Comment by cesarga** [comment]
There's a quick [fix](https://github.com/Akryum/vue-cli-plugin-apollo/issues/58#issuecomment-422779683) by modifying the webpack config.

In resolve.extensions put .mjs before .js

```js
  resolve: {

    // ...

    extensions: [
      '.mjs',
      '.js',
      '.jsx',
      '.vue',
      '.json'
    ],

    // ...

  },
```

And you also have to add this rule
```js
  module: {
    rules: [

      // ...

      {
        test: /\.mjs$/,
        type: 'javascript/auto',
        include: [
          /node_modules/
        ]
      },

      // ...

    ]
  },
```

**Comment by aldarund** [comment]
@cesarga first fix dont work . As for second, its not a fix, it will threat mjs as javascript so the meaning of mjs will be totally lost and will break some other libs that rely on it

**Comment by cesarga** [comment]
@aldarund the first one is for vue-cli, I supposed it didn't work for nuxt as is. As for the second, you can scope the mjs that need to be treated as js (or not) using include and exlude; or even create separate rules according to your needs.

**Comment by aldarund** [comment]
If mjs should be threated js it  should be js, not mjs.

**Comment by Akryum** [comment]
It should be fixed in latest release.

**Comment by aldarund** [comment]
@benmccallum try nuxt appolo 4.0.0-rc3
