### ISSUE TITLE
flatmap-stream malicious package

### ISSUE THREAD

**Issue by nomadoda** [Akryum/vue-cli-plugin-apollo#75]
Critical: Malicious Package
Package: flatmap-stream 
Patched in: No patch available
Dependency of: vue-cli-plugin-apollo 
Path: vue-cli-plugin-apollo > nodemon > pstree.remy > ps-tree > event-stream > flatmap-stream
More info: https://nodesecurity.io/advisories/737

Fix?

**Comment by Akryum** [comment]
Nodemon was patched literally a minute ago: https://github.com/remy/nodemon/pull/1470
