### ISSUE TITLE
FormatError & MiddleWare

### ISSUE THREAD

**Issue by betaSavvy** [Akryum/vue-cli-plugin-apollo#76]
Hi,

I am quite new so was trying out the vue-cli-plugin-apollo and added apollo-server.

So my question is:
1. How do we actually add middleware in this(want to install helmet)?
2. How do we formatError?

**Comment by Durss** [comment]
You can add a middleware on the server.js file by adding an app.use( .... ) if you want.

But if you want it to be called AFTER the apollo's middleware, good luck :/

I wanted to use this middleware to optimise a JSON before sending it to client
https://github.com/gajus/graphql-deduplicator#server-side

But no success so far. Middlewares from server.js are added before apollo's and i can't find any way to achieve that.

According to the module i want to use, for your specific case you should be able to do something like this but i couldn't make it work :

```
	app.use('/graphql', graphqlExpress((request, response) => {
		return {
			formatResponse: (response) => {
				//Format
				return response;
			}
		};
	}));
```

**Comment by Akryum** [comment]
Use [Apollo Server options](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#constructoroptions-apolloserver) in `vue.config.js`. [Docs](https://vue-cli-plugin-apollo.netlify.com/guide/configuration.html#plugin-options).
