### ISSUE TITLE
Install generator breaks immediately on install when using Typescript.

### ISSUE THREAD

**Issue by AnalyzePlatypus** [Akryum/vue-cli-plugin-apollo#77]
When adding `vue-cli-plugin-apollo` to a Vue project that is using Typescript, the generated code breaks the build with several type and import syntax errors.

```
ERROR in /src/main.ts
3:32 Could not find a declaration file for module './vue-apollo.js'. '/src/vue-apollo.js' implicitly has an 'any' type.
    1 | import Vue from 'vue'
    2 | import App from './App.vue'
  > 3 | import { createProvider } from './vue-apollo.js'
      |                                ^
    4 | 
    5 | Vue.config.productionTip = false
    6 | 

ERROR in /src/main.ts
8:3 Argument of type '{ apolloProvider: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Object literal may only specify known properties, and 'apolloProvider' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
     6 | 
     7 | new Vue({
  >  8 |   apolloProvider: createProvider(),
       |   ^
     9 |   render: h => h(App)
    10 | }).$mount('#app')
    11 | 
Version: typescript 3.2.2
Time: 1311ms
```

## System
```
$ vue --version
3.2.1
```
```
// From package.json
"vue-apollo": "^3.0.0-beta.11"
```

## Steps To Reproduce
1.`vue create apollo-issues`
2. In the interactive prompt, select `"Manually Select Features"`, and select `TypeScript`.
3. `cd apollo-issues`
4. `npm run serve`. Observe that the build is fine. 
5. `vue add apollo`. The build breaks with the two errors `Could not find a declaration file for module './vue-apollo.js'.` and `Argument of type '{ apolloProvider:..does not exist in type...`

### Expected
Build to continue working with no errors (And a working GraphQL client... :) )

### Actual
Build breaks with two errors.

## Discussion
I don't have a fix for the import errors yet (I'm rather new to TypeScript), but either way the faulty generated code has got to go.

# Solution
See below.

## Relevant Resources/Articles
- None

**Comment by AnalyzePlatypus** [comment]
## To fix this issue in a project

1. Configure TypeScript to allow implicit `any` types (this will allow TypeScript to call into untyped JavaScript without typings. This is a band-aid, not a cure)
```
// in your tsconfig.json, add this root key
{
...
"noImplicitAny": false,
...
}
```

2. Fix the syntax error in the generated changes to `main.ts`.
```
// in main.ts

// OLD
{
...
apolloProvider: createProvider(),
...
}

// NEW
...
provide: createProvider(),
...
}
```

That solves the build issue for me.

The generator should be updated to use the correct `provide` syntax in `main.ts`.

**Comment by Akryum** [comment]
The correct syntax is `apolloProvider: createProvider()`.

**Comment by AnalyzePlatypus** [comment]
I can confirm that this issue is resolved as of version `3.0.0-beta.11`.
The default generated code no longer raises any errors.

This issue can be closed.

**Comment by benchik** [comment]
I have 
"vue-apollo": "^3.0.2",
"vue-cli-plugin-apollo": "^0.21.3"

and this issue still seems to happen

**Comment by AnalyzePlatypus** [comment]
What does your `main.ts` look like?
And exactly what error are you getting?

**Comment by benchik** [comment]
My `main.ts` is:
`import Vue from 'vue';
import App from './App.vue';
import router from './router';
import { createProvider } from './vue-apollo';

Vue.config.productionTip = false;

new Vue({
  router,
  apolloProvider: createProvider(),
  render: (h:any) => h(App),
}).$mount('#app');
`
and the errors are:

`ERROR in D:/.../src/main.ts(4,32):
4:32 Could not find a declaration file for module './vue-apollo'. 'D:/programming/OU/Yachad/mars-new/mars/src/vue-apollo.js' implicitly has an 'any' type.
    2 | import App from './App.vue';
    3 | import router from './router';
  > 4 | import { createProvider } from './vue-apollo';
      |                                ^
    5 | 
    6 | Vue.config.productionTip = false;
    7 | 
ERROR in D:/.../src/main.ts(10,3):
10:3 Argument of type '{ router: VueRouter; apolloProvider: any; render: (h: any) => any; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Object literal may only specify known properties, and 'apolloProvider' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, 
any>>, Record<string, any>>'.
     8 | new Vue({
     9 |   router,
  > 10 |   apolloProvider: createProvider(),
       |   ^
    11 |   render: (h:any) => h(App),
    12 | }).$mount('#app');
    13 | 
Version: typescript 3.5.3`

if i change the vue-apollo.js to vue-apollo.ts i get errors for missing type definitions for vue-apollo.ts

**Comment by benchik** [comment]
Adding `"allowJs: true"` did the trick, but doesn't the whole point is to have type definitions so vue-apollo can be a ts file?

**Comment by marhub** [comment]
Any luck solving this ?

**Comment by alecmarcus** [comment]
I'm experiencing this issue as well.

**main.ts**
```TS
import Vue from "vue";
import VueCompositionApi from "@vue/composition-api";
import App from "./App";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";
import { createProvider } from "./vue-apollo";

Vue.config.productionTip = false;
Vue.use(VueCompositionApi);

new Vue({
  router,
  store,
  apolloProvider: createProvider(),
  render: h => h(App)
}).$mount("#app");
```

**tsconfig.json**
```JSON
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "vue-cli-plugin-apollo/types"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ],
      "@/": [
        "src/"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

`"vue-cli-plugin-apollo": "~0.21.3",`
`"vue-apollo": "^3.0.0-beta.11",`

**Error**
```
Could not find a declaration file for module './vue-apollo'. '/src/vue-apollo.js' implicitly has an 'any' type.ts(7016)
```

**Comment by josephlbarnett** [comment]
adding:
```
  "files": [
    "node_modules/vue-cli-plugin-apollo/types.d.ts"
  ]
```
to `tsconfig.json` appears to fix the type definitions in vue-apollo.ts for me

**Comment by connorshea** [comment]
You can alternatively resolve this by enabling type acquisition in your `tsconfig.json`, rather than adding the `files` array:

```json
"typeAcquisition": {
  "enable": true
}
```
