### ISSUE TITLE
Error: Expecting a parsed GraphQL document

### ISSUE THREAD

**Issue by jantajov** [Akryum/vue-cli-plugin-apollo#78]
I am trying to use apollo in my new project but I always get an error:
`Error: Expecting a parsed GraphQL document`

My smart query definition is following:
```js
<script>
  import query from '@/graphql/queries/GetPokemon.graphql'

  export default {
    name: 'HelloWorld',
    props: {
      msg: String
    },
    apollo: {
      pokemons: {
        query
      }
    }
  }
</script>
```

GrqphQl query
```graphql
query {
    pokemons(first: 10) {
        id
        name
    }
}
```

I also create minimal project to reproduce this error:
[min-reproduc.zip](https://github.com/Akryum/vue-cli-plugin-apollo/files/2675251/min-reproduc.zip)

Just extract, and `npm install && npm run serve`

**Comment by Akryum** [comment]
Should be fixed in upcoming release.
