### ISSUE TITLE
Error while loading rule 'graphql/template-strings': Multiple options for GraphQL tag ESLintPluginGraphQLFile

### ISSUE THREAD

**Issue by JimmieMax** [Akryum/vue-cli-plugin-apollo#80]
When I run this server it happened

**Comment by JimmieMax** [comment]
I already knew the reason of this issues is that I run "vue add vue-apollo" twice,and it add 
"{
          "env": "literal",
          "projectName": "app"
        }"
twice, HaHaHa

**Comment by josephpierres** [comment]
in eslintrc.js
