### ISSUE TITLE
Add a way to set a custom middleware for refreshing the access token

### ISSUE THREAD

**Issue by lassesteffen** [Akryum/vue-cli-plugin-apollo#86]
Currently we are not able to add a custom middleware for e. g. refreshing an access token. This stems from the fact, that the authLink is the first link, and I can not easily add another link before this authLink (which sets the token).

Am I missing something or is there just no support for this?

**Comment by Akryum** [comment]
Do you have an example of how it would look like?

**Comment by lassesteffen** [comment]
Thanks for the response! This is what I need and what I was not able to build with this plugin. I think the example is pretty : straight forward: 

```
const refreshTokenLink = setContext(() => AuthenticationService.renewSessionIfExpired());

const authLink = setContext((_, { headers }) => {
  const { accessToken } = store.state.user;
  const newHeaders = {
    ...headers,
  };
  if (accessToken !== null) {
    newHeaders['authorization'] = `JWT ${accessToken}`;
  }

  return {
    headers: newHeaders,
  };
});

const httpLink = createUploadLink({ uri: httpEndpoint });

const link = ApolloLink.from([refreshTokenLink, authLink, httpLink]);
```

In the code the first link is always the AuthLink. If there would be some option like a `preAuthLink`, that could be passed in that would be awesome.

```
   ....
    const authLinkChain = authLink
    if (preAuthLink) {
       authLinkChain = preAuthLink.concat(authLink)
    }
    
    // Concat all the http link parts
    link = authLinkChain.concat(link)
    ....
  }
```

**Comment by matrunchyk** [comment]
@lassesteffen please take a look on [this](https://github.com/matrunchyk/vue-cli-plugin-apollo/commit/40166f5e058d0f2fbcb038fc9533d4c014b522a6) and check whether it would work for your case.

**Comment by lassesteffen** [comment]
Looks good to me!

**Comment by matrunchyk** [comment]
Great!
@Akryum are you okay with merging the relevant PR then?

**Comment by matrunchyk** [comment]
Maybe other upvoters can also check this @durss, @oller, @madmod, @thetre97

**Comment by boydaihungst** [comment]
@matrunchyk You forgot to add `.concat(link)`
It should be 
```
if (preAuthLinks.length) { 
      link = from(preAuthLinks).concat(link)
}
```
