### ISSUE TITLE
Vue build fails with latest version.

### ISSUE THREAD

**Issue by farcasmihai91** [Akryum/vue-cli-plugin-apollo#92]
I started getting these errors when running npm build:
```
npm run build

> health-plus-v3@0.3.0 build G:\health-plus-v3
> vue-cli-service build


-  Building for production...Invalid .graphqlconfig file
\  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
-  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                 01:02:53

This dependency was not found:

* graphql-anywhere/lib/async in ./node_modules/apollo-link-state/lib/index.js

To install it, you can run: npm install --save graphql-anywhere/lib/async
 ERROR  Build failed with errors.
```

Installed the latest version of the plugin:

`-- vue-cli-plugin-apollo@0.19.1
  +-- apollo-cache-inmemory@1.5.0
  | +-- apollo-cache@1.2.0
  | `-- optimism@0.6.9
  |   `-- immutable-tuple@0.4.10
  +-- apollo-client@2.5.0
  | +-- @types/zen-observable@0.8.0
  | +-- apollo-link-dedup@1.0.15
  | `-- symbol-observable@1.2.0
  +-- apollo-link-context@1.0.14
  +-- apollo-link-persisted-queries@0.2.2
  +-- apollo-link-state@0.4.2
  | `-- graphql-anywhere@4.2.0
  +-- apollo-link-ws@1.0.14
  +-- apollo-server-express@2.4.8
  | +-- @types/accepts@1.3.5
  | +-- @types/body-parser@1.17.0
  | | `-- @types/connect@3.4.32
  | +-- @types/cors@2.8.4
  | +-- @types/express@4.16.1
  | | +-- @types/express-serve-static-core@4.16.1
  | | | `-- @types/range-parser@1.2.3
  | | `-- @types/serve-static@1.13.2
  | |   `-- @types/mime@2.0.1
  | `-- cors@2.8.5
  +-- apollo-upload-client@10.0.0
  | +-- apollo-link-http-common@0.2.10
  | `-- extract-files@5.0.1
  +-- deepmerge@3.2.0
  +-- esm@3.2.7
  +-- nodemon@1.18.10
  | +-- ignore-by-default@1.0.1
  | +-- pstree.remy@1.1.6
  | +-- touch@3.1.0
  | | `-- nopt@1.0.10
  | +-- undefsafe@2.0.2
  | | `-- debug@2.6.9
  | |   `-- ms@2.0.0
  | `-- update-notifier@2.5.0
  |   +-- boxen@1.3.0
  |   | +-- ansi-align@2.0.0
  |   | | `-- string-width@2.1.1
  |   | |   +-- is-fullwidth-code-point@2.0.0
  |   | |   `-- strip-ansi@4.0.0
  |   | |     `-- ansi-regex@3.0.0
  |   | +-- camelcase@4.1.0
  |   | +-- cli-boxes@1.0.0
  |   | +-- string-width@2.1.1
  |   | | +-- is-fullwidth-code-point@2.0.0
  |   | | `-- strip-ansi@4.0.0
  |   | |   `-- ansi-regex@3.0.0
  |   | +-- term-size@1.2.0
  |   | | `-- execa@0.7.0
  |   | |   +-- cross-spawn@5.1.0
  |   | |   | `-- lru-cache@4.1.5
  |   | |   |   `-- yallist@2.1.2
  |   | |   `-- get-stream@3.0.0
  |   | `-- widest-line@2.0.1
  |   |   `-- string-width@2.1.1
  |   |     +-- is-fullwidth-code-point@2.0.0
  |   |     `-- strip-ansi@4.0.0
  |   |       `-- ansi-regex@3.0.0
  |   +-- configstore@3.1.2
  |   | `-- unique-string@1.0.0
  |   |   `-- crypto-random-string@1.0.0
  |   +-- import-lazy@2.1.0
  |   +-- is-npm@1.0.0
  |   +-- latest-version@3.1.0
  |   | `-- package-json@4.0.1
  |   |   +-- got@6.7.1
  |   |   | +-- create-error-class@3.0.2
  |   |   | | `-- capture-stack-trace@1.0.1
  |   |   | +-- duplexer3@0.1.4
  |   |   | +-- get-stream@3.0.0
  |   |   | +-- is-redirect@1.0.0
  |   |   | +-- is-retry-allowed@1.1.0
  |   |   | +-- lowercase-keys@1.0.1
  |   |   | +-- timed-out@4.0.1
  |   |   | +-- unzip-response@2.0.1
  |   |   | `-- url-parse-lax@1.0.0
  |   |   |   `-- prepend-http@1.0.4
  |   |   +-- registry-auth-token@3.3.2
  |   |   | `-- rc@1.2.8
  |   |   |   +-- deep-extend@0.6.0
  |   |   |   `-- minimist@1.2.0
  |   |   `-- registry-url@3.1.0
  |   +-- semver-diff@2.1.0
  |   `-- xdg-basedir@3.0.0
  `-- ts-node@7.0.1
    +-- minimist@1.2.0
    `-- yn@2.0.0

Any ideas? 
Thanks!

**Comment by i-hardy** [comment]
Having the same issue with a project I started prototyping this morning.

**Comment by farcasmihai91** [comment]
In the meantime I switched back to using vue-apollo the regular way since I don't want to worry about the versions of this library in my CD pipeline.

**Comment by Akryum** [comment]
Please provide a reproduction as I can't reproduce this issue on my computer.
